#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 30 11:57:57 CEST 2024
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim top_module_csa_mp_TB_behav -key {Behavioral:sim_1:Functional:top_module_csa_mp_TB} -tclbatch top_module_csa_mp_TB.tcl -log simulate.log"
xsim top_module_csa_mp_TB_behav -key {Behavioral:sim_1:Functional:top_module_csa_mp_TB} -tclbatch top_module_csa_mp_TB.tcl -log simulate.log

