webtalk_init -webtalk_dir /home/wiktoria/Documents/slajdy/complex digital design/labs/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/top_module_mpadder_sub_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May  1 17:34:07 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "62d06994-248d-4eb0-8770-ee1d6961c8f7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5f04df16d6594e898af5f3af45285e6e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "55" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4100.297 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "20.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "9 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115272_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4037362879 -regid "" -xml /home/wiktoria/Documents/slajdy/complex digital design/labs/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/top_module_mpadder_sub_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/wiktoria/Documents/slajdy/complex digital design/labs/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/top_module_mpadder_sub_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/wiktoria/Documents/slajdy/complex digital design/labs/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/top_module_mpadder_sub_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
